name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20] # Define the Node.js version

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Step 3: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Step 5: Run Build
      - name: Run Build
        run: pnpm run build

      # Step 6: Run Tests
      - name: Run tests
        run: pnpm test -- --run
